{{- if .Values.service.mail.enabled }}
{{- if .Values.service.mail.imap.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-imap
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.service.mail.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.service.mail.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.mail.type }}
  {{- if and .Values.service.mail.clusterIP (eq .Values.service.mail.type "ClusterIP") }}
  clusterIP: {{ .Values.service.mail.clusterIP }}
  {{- end }}
  {{- if .Values.service.mail.sessionAffinity }}
  sessionAffinity: {{ .Values.service.mail.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.mail.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.service.mail.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.service.mail.type "LoadBalancer") (eq .Values.service.mail.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.mail.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.mail.type "LoadBalancer") (not (empty .Values.service.mail.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.mail.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.service.mail.type "LoadBalancer") (not (empty .Values.service.mail.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.mail.loadBalancerIP }}
  {{- end }}
  ports:  
    - name: imap
      port: {{ .Values.service.mail.imap.port }}
      targetPort: {{ .Values.service.mail.imap.targetPort }}
      {{- if (and (or (eq .Values.service.mail.type "NodePort") (eq .Values.service.mail.type "LoadBalancer")) (not (empty .Values.service.mail.imap.nodePort))) }}
      nodePort: {{ .Values.service.mail.imap.nodePort }}
      {{- else if eq .Values.service.mail.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.service.mail.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.service.mail.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}  
{{- end }}
{{- end }}